### ISSUE TITLE
Should isPrefixOf come from Data.List?

### ISSUE THREAD

**Issue by peti** [minad/intro#1]
Hi,

I'm currently exploring the different alternative Preludes out there using [this list](https://guide.aelve.com/haskell/alternative-preludes-zr69k1hc) to guide me. I have to say that I like Intro a lot. The feature I appreciate the most is that you list all exported functions *explicitly* to provide usable Haddock documentation. That makes your library just so much easier to use than most of the others.

Now, my main interest pursuing other Preludes is in consistent support of `Text` rather than `String`. Intro goes a long way to wards that end. I noticed, though, that some functions like `isPrefixOf` are exported from `Data.List` by default. Personally, I've found that I use that function almost always for String operations and therefore I'd be much happier to have the version from `Data.Text` in scope by default. Do you have any thoughts on that issue? Do you apply some guiding principle to make these kind of choices that I am not aware of?

Best regards,
Peter

**Comment by minad** [comment]
Thank you! Actually, intro was a good learning experience to check the prelude functions for totality :) I did't want to change many things, just use it as a saner single-file drop in replacement for the standard prelude.

Concerning Text functions, I usually import those qualified since there are just too many name clashes (with list but also with bytestring). To emphasize Text usage, I replaced the Prelude String functions with their Text variants (Similar to protolude). However, right now the preference is on Data.List functions exported unqualified, since this is consistent with the standard prelude. No Data.Text.* functions are exported by default. It might make sense to selectively export a few functions from Data.Text instead of their List counterpart, as you suggest, if they seem to be more useful for Text. It depends on what you value more - consistency in the Text imports or a few unqualified Text function calls. In the end it is a matter of taste, I guess that is one reason for the plethora of custom preludes (and maybe also because the standard prelude contains "bad" functions).

I usually write my custom five line project prelude on top of intro, which does minor tweaking, importing lens, orphans etc. So you could for sure do that in that case or even use a forked version in your projects. I mean intro is nearly single file after all. In my projects I found that there are nearly no explicit base imports, only imports of project modules, so I guess the current scheme is pretty convenient for me.

**Comment by peti** [comment]
I see your point. It's hard to choose between the List and Text functions and which way you go really depends on the project you're working on. A project-specific mini-prelude is definitely the way to go.

Anyway, thank you very much! :-)
